run:
  timeout: 5m
  go: "1.26"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - copyloopvar
    - dogsled
    - dupl
    - gocritic
    - gofmt
    - goimports
    - goprintffuncname
    - misspell
    - nakedret
    - prealloc
    - revive
    - unconvert
    - whitespace

linters-settings:
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - dupImport

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
    - path: internal/core/.*_darwin\.go
      linters:
        - gocritic
    - path: internal/core/.*_windows\.go
      linters:
        - gocritic
