package webview

import (
	"fmt"
	"reflect"
	"strings"
)

// Binding represents a registered JS-to-Go function binding.
type Binding struct {
	Name string
	Fn   any
}

// GenerateTS produces TypeScript definitions for the given bindings.
func GenerateTS(bindings ...Binding) (string, error) {
	var b strings.Builder
	b.WriteString("// Generated by webviewgo. Do not edit.\n\n")
	b.WriteString("interface Window {\n")

	for _, binding := range bindings {
		ts, err := bindingToTS(binding)
		if err != nil {
			return "", fmt.Errorf("webview: GenerateTS for %q: %w", binding.Name, err)
		}
		b.WriteString("  ")
		b.WriteString(ts)
		b.WriteString("\n")
	}

	b.WriteString("}\n")
	return b.String(), nil
}

func bindingToTS(binding Binding) (string, error) {
	if binding.Name == "" {
		return "", fmt.Errorf("binding name is required")
	}
	if binding.Fn == nil {
		return "", fmt.Errorf("binding function is nil")
	}

	fnType := reflect.TypeOf(binding.Fn)
	if fnType.Kind() != reflect.Func {
		return "", fmt.Errorf("binding value is not a function")
	}

	seen := map[reflect.Type]string{}
	var params []string
	nIn := fnType.NumIn()
	for i := 0; i < nIn; i++ {
		paramType := goTypeToTS(fnType.In(i), seen)
		if fnType.IsVariadic() && i == nIn-1 {
			params = append(params, fmt.Sprintf("...arg%d: %s", i, paramType))
			continue
		}
		params = append(params, fmt.Sprintf("arg%d: %s", i, paramType))
	}

	returnType := "void"
	numOut := fnType.NumOut()

	if numOut == 1 {
		if fnType.Out(0) == reflect.TypeOf((*error)(nil)).Elem() {
			returnType = "void"
		} else {
			returnType = goTypeToTS(fnType.Out(0), seen)
		}
	} else if numOut >= 2 {
		lastOut := fnType.Out(numOut - 1)
		if lastOut == reflect.TypeOf((*error)(nil)).Elem() {
			if numOut == 2 {
				returnType = goTypeToTS(fnType.Out(0), seen)
			} else {
				var types []string
				for i := 0; i < numOut-1; i++ {
					types = append(types, goTypeToTS(fnType.Out(i), seen))
				}
				returnType = "[" + strings.Join(types, ", ") + "]"
			}
		} else {
			var types []string
			for i := 0; i < numOut; i++ {
				types = append(types, goTypeToTS(fnType.Out(i), seen))
			}
			returnType = "[" + strings.Join(types, ", ") + "]"
		}
	}

	return fmt.Sprintf("%s(%s): Promise<%s>;", binding.Name, strings.Join(params, ", "), returnType), nil
}

func goTypeToTS(t reflect.Type, seen map[reflect.Type]string) string {
	if t == nil {
		return "any"
	}
	if name, ok := seen[t]; ok {
		if name == "" {
			return "any"
		}
		return name
	}
	switch t.Kind() {
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number"
	case reflect.String:
		return "string"
	case reflect.Bool:
		return "boolean"
	case reflect.Slice, reflect.Array:
		return goTypeToTS(t.Elem(), seen) + "[]"
	case reflect.Map:
		if t.Key().Kind() == reflect.String {
			return fmt.Sprintf("Record<string, %s>", goTypeToTS(t.Elem(), seen))
		}
		return "Record<string, any>"
	case reflect.Struct:
		return goStructToTS(t, seen)
	case reflect.Interface:
		return "any"
	case reflect.Ptr:
		return goTypeToTS(t.Elem(), seen)
	case reflect.Func:
		return "Function"
	case reflect.Chan:
		return "any"
	default:
		return "any"
	}
}

func goStructToTS(t reflect.Type, seen map[reflect.Type]string) string {
	seen[t] = ""
	if t.NumField() == 0 {
		seen[t] = "object"
		return "object"
	}
	var fields []string
	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)
		if !field.IsExported() {
			continue
		}
		name := field.Name
		jsonTag := field.Tag.Get("json")
		if jsonTag != "" {
			parts := strings.Split(jsonTag, ",")
			if parts[0] == "-" {
				continue
			}
			if parts[0] != "" {
				name = parts[0]
			}
		}
		fields = append(fields, fmt.Sprintf("%s: %s", name, goTypeToTS(field.Type, seen)))
	}
	s := "{ " + strings.Join(fields, "; ") + " }"
	seen[t] = s
	return s
}
